name: PartyAnimals
version: "${version}"
main: org.maboroshi.partyanimals.PartyAnimals
loader: org.maboroshi.partyanimals.Loader
description: A fun pinata plugin for custom server events and automated vote rewards. Supports custom entity models and unique escape mechanisms.
author: Maboroshi
website: https://github.com/MaboroshiKobo/PartyAnimals
api-version: "26.1"
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    Votifier:
      load: BEFORE
      required: false
    ModelEngine:
      load: BEFORE
      required: false
    BetterModel:
      load: BEFORE
      required: false